### ISSUE TITLE
"no such file or directory" when tempFileHandler.js is trying to delete tmp file

### ISSUE THREAD

**Issue by wbulot** [richardgirges/express-fileupload#211]
Hi,

I notice that sometimes my node process crash with the following error : 

```
/usr/src/app/node_modules/express-fileupload/lib/tempFileHandler.js:49
      deleteFile(tempFilePath, (err) => { if (err) throw err; });
                                                   ^

[Error: ENOENT: no such file or directory, unlink '/tmp/tmp-1703-1586272253863'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/tmp/tmp-1703-1586272253863'
}
```
I'm using the current GitHub version.
I don't know how to reproduce the issue.
My application handle high upload traffic. Maybe it happens only when the server is stress tested.
Anyway is it possible to check if the file exist before trying to delete it ?

Thanks

**Comment by RomanBurunkov** [comment]
Do you manually removing temporary files?
It looks you do

**Comment by wbulot** [comment]
I have a function that "truncate" tmp file when they are stuck (did that because of https://github.com/richardgirges/express-fileupload/issues/148)
But I don't delete them.

Could that be related ?

**Comment by RomanBurunkov** [comment]
What do u mean 'truncate'?

Any way the #148 issue now resolved in the latest versions.
Middleware now have internal checks for canceled uploads and delete stuck temp files.

Please try to stop truncating.

**Comment by wbulot** [comment]
By truncate I mean this : http://man7.org/linux/man-pages/man2/ftruncate.2.html
So basically after truncating the tmp file, it still exists but his length is 0 bytes (maybe it is then invisible for express-fileupload I don't know).

Even if https://github.com/richardgirges/express-fileupload/issues/148 fix most zombies tmp files, there is still some cases where I must delete them myself (if node or the system crash during an upload for example).
I'll do some more test about this and close my issue if it is related to the file being truncated.

**Comment by RomanBurunkov** [comment]
That should be fixed in 1.1.7-alpha.3.
I've removed error throwing.
